[[redirects]]
  from = "/wakatime/"
  to = "https://wakatime.com/api/v1/"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/country/"
  to = "https://restcountries.com/v2/alpha/"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {Access-Control-Allow-Origin = "*"}
